spring:
  application:
    name: provider-demo
server:
  port: 8078

eurekaServer:
  host: localhost
  port: 8761
  user: root
  password: root
eureka:
  client:
    register-with-eureka: true
    service-url:
     defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/eureka
