spring:
  application:
    name: consumer-demo
server:
  port: 8088

  #为服务Id名称为provider-demo的项目配置负载均衡规则为com.netflix.loadbalancer.WeightedResposneTimeRule

provider-demo:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule